[package]
name = "mattpaint"
version = "1.0.0"
description = "MattPaint: Microsoft Paint (Windows 10), for Mac and Windows"
edition = "2021"
license = "MIT"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-opener = "2"
base64 = "0.22"
wallpaper = "3"

[profile.release]
lto = true
opt-level = "s"
strip = true
